[package]
name = "guessing_game"
version = "0.1.0"
authors = ["Samuel Berger"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

#Use the rand crate with version 0.3.14.
rand = "0.4.0"
#rand = ""